/**
 * Generate docs/scorecard.json and splice autogenerated sections into
 * docs/PROVIDER_SCORECARD.md between `<!-- BEGIN:... -->` / `<!-- END:... -->`
 * markers.
 *
 * Markers the generator looks for:
 *   AUTOGEN_VERIFIED_AT          — the dated line under §2
 *   AUTOGEN_SCORECARD_TABLE      — the 10-row comparative table
 *   AUTOGEN_DETAILED_RATINGS     — the §3 per-provider block
 *   AUTOGEN_GOTCHAS              — the §5 gotchas table
 *
 * Run: pnpm scorecard:generate
 */

import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { computeScores } from "./compute.js";
import { DOCS_DIR, loadProviders } from "./load.js";
import {
  type ScoredProvider,
  buildScorecardJson,
  rankProviders,
  renderDetailedRatings,
  renderGotchasTable,
  renderReadmeTable,
  renderScorecardTable,
} from "./render.js";

const SCORECARD_MD = join(DOCS_DIR, "PROVIDER_SCORECARD.md");
const SCORECARD_JSON = join(DOCS_DIR, "scorecard.json");
const HISTORY_JSON = join(DOCS_DIR, "scorecard-history.json");
const README_MD = join(DOCS_DIR, "..", "README.md");

interface MarkerReplacement {
  readonly name: string;
  readonly content: string;
}

function splice(
  markdown: string,
  replacements: readonly MarkerReplacement[],
): string {
  let out = markdown;
  for (const r of replacements) {
    const begin = `<!-- BEGIN:${r.name} -->`;
    const end = `<!-- END:${r.name} -->`;
    const pattern = new RegExp(
      `${escapeRegex(begin)}[\\s\\S]*?${escapeRegex(end)}`,
      "m",
    );
    if (!pattern.test(out)) {
      throw new Error(
        `Missing marker pair for "${r.name}" in PROVIDER_SCORECARD.md`,
      );
    }
    out = out.replace(pattern, `${begin}\n${r.content}\n${end}`);
  }
  return out;
}

function escapeRegex(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

function loadLatestHistoryEntry(): {
  scorecard_version: string;
  rubric_version: string;
} {
  const raw = readFileSync(HISTORY_JSON, "utf8");
  const parsed = JSON.parse(raw) as {
    history: Array<{
      scorecard_version?: string;
      rubric_version?: string;
    }>;
  };
  const latest = parsed.history.at(-1);
  if (
    !latest ||
    typeof latest.scorecard_version !== "string" ||
    typeof latest.rubric_version !== "string"
  ) {
    throw new Error(
      "scorecard-history.json: last entry missing scorecard_version / rubric_version",
    );
  }
  return {
    scorecard_version: latest.scorecard_version,
    rubric_version: latest.rubric_version,
  };
}

function main(): void {
  const providers = loadProviders();
  if (providers.length === 0) {
    throw new Error(
      "No provider YAML files found in docs/scorecard/providers/",
    );
  }

  const scored: ScoredProvider[] = providers.map((p) => ({
    yaml: p.yaml,
    scores: computeScores(p.yaml),
  }));
  const ranked = rankProviders(scored);

  const versions = loadLatestHistoryEntry();
  const verifiedAt = ranked[0]?.yaml.verified_at;
  if (!verifiedAt) {
    throw new Error("Cannot determine verified_at");
  }
  const allSameDate = ranked.every((p) => p.yaml.verified_at === verifiedAt);
  if (!allSameDate) {
    throw new Error(
      "All provider YAMLs must share the same verified_at (mixed audit dates). Update every file or bump the scorecard version.",
    );
  }

  const markdown = readFileSync(SCORECARD_MD, "utf8");
  const updated = splice(markdown, [
    {
      name: "AUTOGEN_VERIFIED_AT",
      content: `*Verified: **${verifiedAt}** — rubric v${versions.rubric_version}, scorecard v${versions.scorecard_version}*`,
    },
    {
      name: "AUTOGEN_SCORECARD_TABLE",
      content: renderScorecardTable(ranked),
    },
    {
      name: "AUTOGEN_DETAILED_RATINGS",
      content: renderDetailedRatings(ranked),
    },
    {
      name: "AUTOGEN_GOTCHAS",
      content: renderGotchasTable(ranked),
    },
  ]);

  if (updated !== markdown) {
    writeFileSync(SCORECARD_MD, updated);
  }

  const readme = readFileSync(README_MD, "utf8");
  const readmeUpdated = splice(readme, [
    { name: "AUTOGEN_README_SCORECARD", content: renderReadmeTable(ranked) },
  ]);
  if (readmeUpdated !== readme) {
    writeFileSync(README_MD, readmeUpdated);
  }

  const json = buildScorecardJson(ranked, {
    verified_at: verifiedAt,
    scorecard_version: versions.scorecard_version,
    rubric_version: versions.rubric_version,
  });
  writeFileSync(SCORECARD_JSON, `${JSON.stringify(json, null, 2)}\n`);

  // eslint-disable-next-line no-console
  console.log(
    `Generated scorecard.json + updated PROVIDER_SCORECARD.md + README.md (${ranked.length} providers, verified ${verifiedAt}).`,
  );
}

main();
