/**
 * Zod schema for provider scorecard YAML files.
 *
 * One YAML per provider lives in docs/scorecard/providers/{slug}.yaml.
 * Each describes evidence for every sub-criterion / band in the rubric
 * (docs/SCORECARD_RUBRIC.md). The generator in generate.ts consumes these
 * to produce docs/scorecard.json and the autogenerated sections of
 * docs/PROVIDER_SCORECARD.md. The validator in validate.ts re-runs the
 * score math and checks schema conformance + cross-file invariants.
 *
 * The primary YAML IS the source of truth. The rendered markdown and
 * scorecard.json are derived artifacts.
 */

import { z } from "zod";

const url = z.string().url();

// Stable identifiers keyed per dimension — the generator uses these to
// look up the canonical sub-criterion labels in render.ts.
export const D1_IDS = [
  "task_crud",
  "container_crud",
  "core_fields_80pct",
  "native_subtasks",
  "no_ops_gap",
] as const;
export const D2_IDS = [
  "single_api_model",
  "vendor_sdk_fresh",
  "changelog_active",
  "standard_richtext",
  "standard_pagination",
] as const;
export const D6_IDS = [
  "pat",
  "oauth2",
  "pat_self_serve",
  "oauth_self_serve",
  "enterprise_auth",
] as const;
export const D8_IDS = [
  "official_mcp",
  "public_ai_api",
  "agent_entity_lifecycle",
  "production_signals",
] as const;

// D8 sub-criteria carry 1 or 2 points each per the rubric.
export const D8_POINTS: Record<(typeof D8_IDS)[number], 1 | 2> = {
  official_mcp: 2,
  public_ai_api: 1,
  agent_entity_lifecycle: 1,
  production_signals: 1,
};

const SubCriterion = z.object({
  id: z.string(),
  met: z.boolean(),
  evidence: url.optional(),
  note: z.string(),
});

const BandEvidence = z.object({
  band: z.number().int().min(1).max(5),
  justification: z.string(),
  evidence: url.optional(),
});

const RateLimitsEvidence = z.object({
  effective_ops_per_min: z.number().nonnegative(),
  tier_scored: z.string(),
  formula: z.string(),
  justification: z.string(),
  evidence: url.optional(),
});

const RealTimeEvidence = z.object({
  band: z.number().int().min(1).max(5),
  event_count: z.number().int().nonnegative(),
  justification: z.string(),
  evidence: url.optional(),
});

function subCriteriaFor<T extends readonly string[]>(ids: T) {
  return z
    .array(SubCriterion)
    .length(ids.length)
    .refine(
      (arr) => ids.every((id, i) => arr[i]?.id === id),
      (arr) => ({
        message: `sub_criteria must appear in the exact order: ${ids.join(", ")}. Got: ${arr.map((c) => c.id).join(", ")}`,
      }),
    );
}

export const ProviderYAMLSchema = z.object({
  name: z.string().min(1),
  slug: z
    .string()
    .regex(/^[a-z][a-z0-9-]*$/, "slug must be lowercase kebab-case"),
  medal: z.enum(["gold", "silver", "bronze"]).nullable().optional(),
  verified_at: z
    .string()
    .regex(/^\d{4}-\d{2}-\d{2}$/, "verified_at must be YYYY-MM-DD"),
  // Short tag for the README at-a-glance table — 1–5 words, e.g.
  // "AI agents, modern DX".
  best_for: z.string().min(1).max(60),
  bottom_line: z.string().min(1),
  gotcha: z.string().min(1),
  scores: z.object({
    api_completeness: z.object({ sub_criteria: subCriteriaFor(D1_IDS) }),
    api_ergonomics: z.object({ sub_criteria: subCriteriaFor(D2_IDS) }),
    schema_flexibility: BandEvidence,
    rate_limits: RateLimitsEvidence,
    real_time: RealTimeEvidence,
    auth_simplicity: z.object({ sub_criteria: subCriteriaFor(D6_IDS) }),
    data_portability: BandEvidence,
    ai_agent_readiness: z.object({ sub_criteria: subCriteriaFor(D8_IDS) }),
  }),
});

export type ProviderYAML = z.infer<typeof ProviderYAMLSchema>;
export type SubCriterionT = z.infer<typeof SubCriterion>;

/**
 * Map effective ops/min to a band per rubric §3 D4. Pure function so the
 * validator can cross-check the stated band against the numeric evidence.
 */
export function bandFromOpsMin(opsPerMin: number): 1 | 2 | 3 | 4 | 5 {
  if (opsPerMin >= 1000) return 5;
  if (opsPerMin >= 500) return 4;
  if (opsPerMin >= 150) return 3;
  if (opsPerMin >= 50) return 2;
  return 1;
}

/**
 * Map event count to a band per rubric §3 D5 (numeric component only —
 * validator still trusts the stated band for qualitative factors like
 * "covers all major entities" and "delivery retries documented").
 */
export function bandCeilFromEventCount(count: number): 1 | 2 | 3 | 4 | 5 {
  if (count >= 30) return 5;
  if (count >= 15) return 4;
  if (count > 0) return 3;
  return 1;
}
